dataset:
  data_root: C:\DATA\Projects\AutoVisionAI\data
  images_folder: images
  masks_folder: masks
  test_data_root: C:\DATA\Projects\AutoVisionAI\tests\test_data
  allowed_extensions:
  - .jpg
  - .jpeg
  - .png
data_augmentation:
  bbox_min_size: 20
  h_flip_prob: 0.5
  random_crop_prob: 0.5
  resize_to: 512
  random_crop_crop_to: 512
dataloader:
  num_workers: 2
datamodule:
  training_set_size: 0.8
unet:
  model:
    in_channels: 3
    n_classes: 1
  optimizer:
    initial_lr: 0.01
    weight_decay: 0.005
  lr_scheduler:
    step_size: 2
    gamma: 0.1
fast_scnn:
  model:
    n_classes: 1
  optimizer:
    initial_lr: 0.01
  lr_scheduler:
    step_size: 3
    gamma: 0.5
mask_rcnn:
  model:
    n_classes: 2
    hidden_size: 256
  optimizer:
    initial_lr: 0.005
    momentum: 0.9
    weight_decay: 0.0005
  lr_scheduler:
    step_size: 1
    gamma: 0.1
trainer:
  max_epoch: 10
  log_every_n_steps: 20
  weights_folder: weights
logging:
  root_dir: C:\DATA\Projects\AutoVisionAI\experiments
  tensorboard:
    use: true
    save_dir: tb_logs
  mlflow:
    use: true
    tracking_uri: http://127.0.0.1:8080
    save_dir: mlruns_logs
  wandb:
    use: true
    log_model: true
    save_dir: wandb_logs
    mode: online
