logging:
  app_logger:
    stdout:
      level: INFO
      format: "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level}</level> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"
      backtrace: true
      diagnose: true
      enqueue: true

    file:
      level: DEBUG
      save_dir: logs
      file_name: app.log
      format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
      rotation: "10 MB"
      retention: "10 days"
      encoding: "utf-8"
      backtrace: true
      diagnose: true
      enqueue: true


  ml_loggers:
    root_dir: ./experiments
    tensorboard:
      use: true
      save_dir: tensorlogs

    mlflow:
      use: true
      tracking_uri: http://localhost:8080
      save_dir: mlruns

    wandb:
      use: true
      log_model: true
      save_dir: wandb
      mode: offline
