global_logger:
  level: INFO
  save_dir: logs
  file_name: app.log
  rotation: 10 MB
  retention: 7 days
  format: "[{time:YYYY-MM-DD HH:mm:ss}] {level} {message}"

ml_loggers:
  tensorboard:
    use: true
    save_dir: tensorlogs

  mlflow:
    use: true
    tracking_uri: http://localhost:8080
    save_dir: mlruns

  wandb:
    use: true
    log_model: true
    save_dir: wandb
    mode: offline
