models:
  unet:
    in_channels: 3
    n_classes: 1
    optimizer:
      initial_lr: 0.01
      weight_decay: 0.005
    lr_scheduler:
      step_size: 2
      gamma: 0.1
  fast_scnn:
    n_classes: 1
    optimizer:
      initial_lr: 0.01
      weight_decay: 0.005
    lr_scheduler:
      step_size: 3
      gamma: 0.5
  mask_rcnn:
    n_classes: 2
    hidden_size: 256
    optimizer:
      initial_lr: 0.005
      momentum: 0.9
      weight_decay: 0.0005
    lr_scheduler:
      step_size: 1
      gamma: 0.1

trainer:
  max_epoch: 10
  log_every_n_steps: 20
  weights_folder: weights
