name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create virtual environment
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -e .

      - name: Install dependencies via uv
        run: |
          uv pip install -e ".[all]"

      - name: Run pre-commit
        run: uv run pre-commit run --all-files -v

      - name: Run tests
        run: |
          uv run pytest tests/ --disable-warnings

      - name: Cache uv
        uses: actions/cache@v3
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}

      - name: Conventional Commitlint
        uses: opensource-nepal/commitlint@v1
