name: Destroy AutoVisionAI Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirmation:
        description: 'Type "DESTROY" to confirm destruction of all resources'
        required: true
        type: string

env:
  AWS_REGION: us-west-1
  TF_VAR_aws_region: us-west-1

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Validate confirmation
      if: ${{ github.event.inputs.confirmation != 'DESTROY' }}
      run: |
        echo "Confirmation failed. You must type 'DESTROY' to proceed."
        exit 1

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.2

    - name: Destroy Infrastructure
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
      run: |
        # Set confirmation to DESTROY for non-interactive execution
        echo "DESTROY" | chmod +x scripts/destroy-infrastructure.sh && ./scripts/destroy-infrastructure.sh $AWS_REGION
